version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.49.2:31112
functions:
  init-config-mongo:
    lang: java11
    handler: ./init-config-mongo
    image: tmsquare/init-config-mongo:latest

