version: 1.0
provider:
  name: openfaas
  gateway: http://34.79.152.252:8080
functions:
  init-config-mongo:
    lang: java11
    handler: ./init-config-mongo
    image: tmsquare/init-config-mongo:latest

