apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv001
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv001
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/station
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv002
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv002
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/auth
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv003
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv003
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/config
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv004
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv004
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/contacts
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv005
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv005
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/insidePayment
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv006
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv006
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/order
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv007
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv007
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/payment
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv008
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv008
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/price
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv009
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv009
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/route
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv010
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv010
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
     # path: /var/nfs/data/security
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv011
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv011
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/train
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv012
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv012
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/travel
      # server: 10.132.0.37
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv013
spec:
    storageClassName: "slow"
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /var/data/mongo/pv013
    # persistentVolumeReclaimPolicy: Retain
    # nfs:
      # path: /var/nfs/data/user
      # server: 10.132.0.37

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-station-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-auth-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-config-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-contacts-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-inside-payment-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-order-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-payment-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-price-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-route-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-security-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-train-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-travel-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-user-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
